service: landingpage

plugins:
  - serverless-domain-manager
  - serverless-finch

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 5
  region: us-east-1

functions:
  hello:
    handler: handler.hello

custom:
  customDomain:
    domainName: api.wdsm.io
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  client:
    bucketName: landing.wdsm.io
